### PR TITLE
Installed Expecta and snapshots

### PR DESCRIPTION
**Pull request by wolffan**
Created testfile for snapshot tests

### CODE REVIEW

**Comment by victorBaro** [comment]
Thanks @wolffan 
Amazing work :D

**Comment by wolffan** [comment]
@victorBaro yeahh!! Happy to help! :+1:

**Comment by victorBaro** [comment]
Can't get tests to work... Specta is giving a weird error... :S
Could you take a look at some point? I have never used specta before.

**Comment by wolffan** [comment]
@victorBaro created a ticket, can you assign to me? also have you registered to Travis to authorise the build?

**Comment by victorBaro** [comment]
Thanks man!
Github doesn't let me assign it to you :/

Yes, I registered. Here is the log: 
screen shot 2015-11-16 at 09 58 04

**Pull request merged**
